// not implemented

D(0,TWOFETCH,    "2@", ( ptr -- ptr[0] ptr[1] ), )
D(0,TWOSTORE,    "2!", ( ptr a b -- ), )
D(0,REPEAT,      "REPEAT",, )
D(0,WHILE,       "WHILE",, )
D(0,UNLOOP,      "UNLOOP",, )
D(0,PLUS_LOOP,   "+LOOP",, )
D(0,LEAVE,       "LEAVE",, )

D(0,MULTDIVMOD,  "*/MOD",, )
D(0,U_DOT,       "U.",, )
D(0,U_LT,        "U<",, )
D(0,UM_MULT,     "UM*",, )
D(0,UM_MOD,      "UM/MOD",, )
D(0,FM_MOD,      "FM/MOD",, )
D(0,SM_REM,      "SM/REM",, )
D(0,M_MULT,      "M*",, )
D(0,SIGN,        "SIGN",, )

D(0,TO_NUMBER,   ">NUMBER",, )
D(0,TO_IN,       ">IN",, )
D(0,QUIT,        "QUIT",, )
D(0,ACCEPT,      "ACCEPT",, )

D(0,DOT_QUOTE,   ".\"",, )
D(0,S_QUOTE,     "S\"",, )
D(0,ABORT_QUOTE, "ABORT\"",, )

D(0,COMPILE_CHAR,"[CHAR]",, )
D(0,CHAR,        "CHAR",, )
D(0,CHAR_PLUS,   "CHAR+",, )
D(0,CHARS,       "CHARS",, )
D(0,COUNT,       "COUNT",, )

D(0,DECIMAL,     "DECIMAL",, )
D(0,HEX,         "HEX",, )
D(0,BASE,        "BASE",, )

D(0,ENVIRONMENTQ,"ENVIRONMENT?",, )

D(0,KEY,         "KEY",, )
D(0,_STATE,      "STATE",, )
D(0,SOURCE,      "SOURCE",, )
D(0,EVALUATE,    "EVALUATE",, )


